#!/bin/bash

export TERM=xterm-256color

echo "CONTAINER DO REACT ESTA DE PÉ"
echo "CONTAINER DO REACT ESTA DE PÉ"
echo "CONTAINER DO REACT ESTA DE PÉ"
echo "CONTAINER DO REACT ESTA DE PÉ"
echo "CONTAINER DO REACT ESTA DE PÉ"
echo "CONTAINER DO REACT ESTA DE PÉ"
echo "CONTAINER DO REACT ESTA DE PÉ"

npm run start