#!/bin/bash

export TERM=xterm-256color

echo "CONTAINER DA API ESTA DE PÉ"
echo "CONTAINER DA API ESTA DE PÉ"
echo "CONTAINER DA API ESTA DE PÉ"
echo "CONTAINER DA API ESTA DE PÉ"
echo "CONTAINER DA API ESTA DE PÉ"
echo "CONTAINER DA API ESTA DE PÉ"
echo "CONTAINER DA API ESTA DE PÉ"

tail -f /dev/null